ci.yml: Update to match new version of the code

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,9 +25,9 @@ jobs:
 
     - name: Run simulation
       run: |
-        mpirun -n 1 ./analysis 256 1 | tee simulation-log.txt
+        mpirun -n 1 ./run mode=sim model=irish simtype=smallsim area=1024 seed=0 period=16 transdata=I,H,reg,cases.txt transdata=H,D,all,deaths.txt housedata=house.txt outputdir=Output | tee simulation-log.txt
         mkdir Simulation
-        cp cases_small.txt houses_small.txt events_small.txt simulation-log.txt Simulation
+        cp cases.txt deaths.txt house.txt simulation-log.txt Simulation
         ls Simulation
 
     - name: Upload simulation results
@@ -38,7 +38,7 @@ jobs:
 
     - name: Run inference
       run: |
-        mpirun -n 1 ./analysis 256 2 50 | tee inference-log.txt
+        mpirun -n 2 ./run mode=mbp model=irish area=1024 nchain=$nprocs nsamp=3 period=16 transdata=I,H,reg,cases.txt transdata=H,D,all,deaths.txt housedata=house.txt outputdir=Output  | tee inference-log.txt
         cp inference-log.txt Output
 
     - name: Upload inference results
@@ -49,11 +49,20 @@ jobs:
 
     - name: Check output files
       run: |
-        required_files="cases_small.txt houses_small.txt events_small.txt Output Output/trace_50.txt Output/R0_50.txt Output/params_50.txt Output/region0_0_data_50.txt Output/region1_0_data_50.txt"
         failures=0
+        required_files="cases.txt deaths.txt house.txt"
 
         for f in $required_files ; do
           if [ ! -r "$f" ]; then
+            echo "Required output file $f not found" >&2
+            failures=$((failures+1))
+          fi
+        done
+
+        required_files="cases_region0_0.txt cases_region0_1.txt cases_region1_0.txt cases_region1_1.txt deaths.txt MCMCdiagnostic.txt parameters.txt R0.txt traceLi.txt trace.txt"
+
+        for f in $required_files ; do
+          if [ ! -r "Output/$f" ]; then
             echo "Required output file $f not found" >&2
             failures=$((failures+1))
           fi
